import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { Nav } from "@/components/nav";
import { Toaster } from "sonner";

const montserrat = Montserrat({
  subsets: ["latin"],
  // Optional: configure weights if you don't want to load all of them
  weight: ["400", "500", "600", "700"],
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: "Cool social media app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} font-sans antialiased`}>
        <Toaster />
        <Nav />
        {children}
      </body>
    </html>
  );
}
